namespace FiscalLabApp.Models;

public enum MenuType
{
    //main page
    MainPageConsultant,
    MainPageAssociation,
    MainPagePlant,
    MainPageInspector,
    MainPageLeader,
    MainPageLaboratoryLeader,

    //cane scale page
    CaneScalePageInScale,
    CaneScalePageOutScale,
    CaneScalePageCargoDraw,
    CaneScalePageScaleObservations,
    CaneScalePageCalibration1,
    CaneScalePageCalibration2,
    CaneScalePageResponsibleBody,
    CaneScalePageCalibrationCertificate,
    CaneScalePageObservations1,
    CaneScalePagePlantPercentage,
    CaneScalePageProviderPercentage,
    CaneScalePagePlantFarmPercentage,
    CaneScalePageFarmProviderPercentage,
    CaneScalePageObservations2,

    //desintegrator probe page
    DesintegratorProbePageProbeTYpe,
    DesintegratorProbePageTubeInserted,
    DesintegratorProbePageTubeDischarged,
    DesintegratorProbePageCollect,
    DesintegratorProbePageSampleAmount,
    DesintegratorProbePageBrothExtraction,
    DesintegratorProbePageLoadPosition,
    DesintegratorProbePageToothedCrown,
    DesintegratorProbePageToothedCrownType,
    DesintegratorProbePageLastCrownChange,
    DesintegratorProbePageObservations3,
    DesintegratorProbePageHomogeneousSamples,
    DesintegratorProbePageKnifeConservation,
    DesintegratorProbePageAgainstKnifeConservation,
    DesintegratorProbePageKnifeAgainstKnifeDistance,
    DesintegratorProbePageHammerConservation,
    DesintegratorProbePageCleanMixer,
    DesintegratorProbePageDesintegratorRpm,
    DesintegratorProbePagePreparationIndex,
    DesintegratorProbePageLastRazorChange,
    DesintegratorProbePageLastHammerChange,
    DesintegratorProbePageLastAgainstKnifeChange,
    DesintegratorProbePageObservations4,

    //analytical balance
    AnalyticalBalanceHomogeneousWeight,
    AnalyticalBalanceFinalWeight,
    AnalyticalBalanceCalibratedBalance,
    AnalyticalBalanceLeveledBalance,
    AnalyticalBalanceCalibrationCertificateBalance,
    AnalyticalBalanceObservations5,
    AnalyticalBalanceAverageAmbientTemperature,
    AnalyticalBalanceObservations6,

    //press refractometer
    PressRefractometerPressureGaugeCertificated,
    PressRefractometerDiscardCup,
    PressRefractometerCollectorBottle,
    PressRefractometerPressure,
    PressRefractometerTimer,
    PressRefractometerPressCleaning,
    PressRefractometerObservations7,
    PressRefractometerBrothHomogenization,
    PressRefractometerRefractometerCalibrationCertificate,
    PressRefractometerPrecisionReading,
    PressRefractometerRefractometerBenchmarking,
    PressRefractometerRefractometerCleaning,
    PressRefractometerInternalTemperature,
    PressRefractometerObservations8,

    //clarification saccharimeter
    ClarificationSaccharimeterBottle,
    ClarificationSaccharimeterAgitation,
    ClarificationSaccharimeterHasDilution,
    ClarificationSaccharimeterClarifier,
    ClarificationSaccharimeterPressure,
    ClarificationSaccharimeterClarifierAmount,
    ClarificationSaccharimeterBottleClarifiedVolume,
    ClarificationSaccharimeterBottleAfterClarifiedVolume,
    ClarificationSaccharimeterObservations9,
    ClarificationSaccharimeterStabilization,
    ClarificationSaccharimeterBenchmarking,
    ClarificationSaccharimeterQuartzPattern,
    ClarificationSaccharimeterQuartzResult,
    ClarificationSaccharimeterQuartzReading,
    ClarificationSaccharimeterCalibrationCertificate,
    ClarificationSaccharimeterTubeCleaning,
    ClarificationSaccharimeterClearCollingCooler,
    ClarificationSaccharimeterObservations10,

    //benchmarking equipment
    BenchmarkingEquipmentLoadCell,
    BenchmarkingEquipmentThermometer,
    BenchmarkingEquipmentTachometer,
    BenchmarkingEquipmentPachymeter,
    BenchmarkingEquipment500Gm,
    BenchmarkingEquipment100Gm,
    BenchmarkingEquipment1Gm,
    BenchmarkingEquipmentSucroseTest,
    BenchmarkingEquipmentRange10,
    BenchmarkingEquipmentRange20,
    BenchmarkingEquipmentRange30,
    BenchmarkingEquipmentZ25,
    BenchmarkingEquipmentZ50,
    BenchmarkingEquipmentZ75,
    BenchmarkingEquipmentZ100,
    BenchmarkingEquipmentObservations11,
    BenchmarkingEquipmentObservations12,
}