on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./FiscalLabApp.sln

      - name: Build
        run: dotnet build ./FiscalLabApp.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./FiscalLabApp.sln --configuration Release -o release --nologo --no-build

      - name: Deploy wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: release/wwwroot
